### ISSUE TITLE
How to reproduce the graphs in the paper?

### ISSUE THREAD

**Issue by khalidan** [nyuwireless/ns3-mmwave#13]
Hi, 

I am working on a school project and as a part of that it requires me to be able to reproduce the graphs in your paper called : "Transport Layer Performance in 5G mmWave Cellular". I was wondering how would I go about doing that? I pulled the latest version of the ns-3.26 and compiled it and went through most of the tutorial (It's so long and provide just the basics to understand the ns-3 simulator). I am looking for a quick way to be able to reproduce those graphs. Is there a way that you can help me with that? It would be highly appreciated. Thank you.

**Comment by MengleiZhang** [comment]
Hi Khalidan,

As you already went through the tutorial, you should notice that ns3 is a powerful simulator capable of simulating realistic networks, but the cost is its complexity. You can use the mmwave-tcp-multilow.cc <http://mmwave-tcp-multilow.cc/> to generate one UE with multiple TCP flows, and mmwave-tcp-multi-ue.cc <http://mmwave-tcp-multi-ue.cc/> to generate multiple UE, each with one TCP flow. The traces can be found in the txt output files. To understand how to interact with the wireless channel, such as simulating building blockage, you can take a look this paper http://dl.acm.org/citation.cfm?id=2915380 <http://dl.acm.org/citation.cfm?id=2915380>.

**Comment by MengleiZhang** [comment]
Hi khalidan,

1. The mmwave-tcp-multiflow.cc example can generate multiple TCP flows for
one UE, and all the flows use the same TCP variant.
2. I think I removed the code which generates UDP traffic. All you need to
do is replace the (BulkSendHelper ftp) application with UDP application.
You may take a look of the LTE example lena-simple-epc.cc, which generates
UDP traffic.
3. If you want to control the source data rate, replace the BulkSendHelper
with OnOffHelper, since the on/off application has attributes to control
sending rate and on/off interval ratio.
4. In the RTT.txt file, at time t, the RTT changed from value of the second
column to the value of the third column.
5. Data.txt returns the packet arriving time and size in Bytes, you should
be able to compute the data rate from that.

**Comment by li654321** [comment]
do you speak chinese?

**Comment by MengleiZhang** [comment]
I do.
 
But for asking questions, please use English so the other developers may also help.

Menglei
