### ISSUE TITLE
slots vs subframes

### ISSUE THREAD

**Issue by biljkus** [nyuwireless/ns3-mmwave#23]
Hi, 

I noticed that there are different parameters in ns3::MmWavePhyMacCommon for configuring the frame stucture. There are SymbolsPerSubframe(24/16), SubframePeriod(100), SymbolPeriod(4.16) which seem sufficient to configure the frame structure. 

But, there are also SlotsPerSubframe and SymbolPerSlot. Are these used for the same frame structure or different? 

If these parameters correspond to different types of frame structure, how can be configured one or another frame structure type?

Thanks,
Biljana

**Comment by MengleiZhang** [comment]
Hi Biljana,

I take a look at these parameters. Turns out some of these parameters are not used but not deleted yet. For example, SlotsPerSubframe and SymbolPerSlot are not used any more.

**Comment by Sourjya9015** [comment]
Just to clarify, the SlotsPerSubframe and SymbolsPerSlot parameters are there so that we can extend the frame structure to a more flexible version with mini-slots. They may not be used now but might be needed later on. 

Although, the concept of slot is there in LTE as well, refer to 3GPP TS 36.211 for details.

**Comment by biljkus** [comment]
Thank you for updates.

Relted  to these configuration parameters, I have noticed that there are some limitations in their configuration, but I do not understand which can and which cannot be modified. E.g. I have tried to configure the frame structure differently but it does not work. The configuration is e.g:

 Config::SetDefault ("ns3::MmWavePhyMacCommon::SymbolPeriod", DoubleValue(16.67)); 
 Config::SetDefault ("ns3::MmWavePhyMacCommon::SymbolsPerSubframe", UintegerValue(4)); 
 Config::SetDefault ("ns3::MmWavePhyMacCommon::SubframePeriod", DoubleValue(71.5));

I get the error: " assert failed. cond="(tag.GetSfn().m_sfNum >= 0) && (tag.GetSfn().m_sfNum < m_phyMacConfig->GetSymbolsPerSubframe ())", file=../src/mmwave/model/mmwave-phy.cc, line=221".

If you have some comments regarding this I would appreciate.

**Comment by Sourjya9015** [comment]
I think this is a configuration error. Because you are changing the parameters, I will ask you to make sure that the numbers add up. Moreover, I think you might also need to re-configure other frame related parameters, line num. of SF in frame etc. to make the model work. 

My suggestion wold be to try to go back to a configuration that worked and figure out whether you are missing any configuration.

**Comment by biljkus** [comment]
You were right. After correctly choosing all parameters, I could run properly the simulation. Thanks!
